# Data Preprocessing Template:

In [39]:
#Importing libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot

In [40]:
#Reading the file(.csv/.xls):
dataset = pd.read_csv('C:/Users/Dell/Desktop/DataScince/02_Pandas/DataSets/Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Step 2: Taking care of the missing numbers from the specific columns:

In [41]:
# #We are using sklearn.preprocessing in Imputer class
# #Now, we are using sklearn.impute, SimpleImputr
# from sklearn.impute import SimpleImputer
# #Make an object of the SimpleImputer class
# si = SimpleImputer(missing_values = np.nan, strategy = 'mean',verbose = 0)
# #using the object fit the columns on which we want to apply this strategy:
# si = si.fit(dataset[['Age','Salary']])
# #Dataset without missing values
# dataset[['Age','Salary']] = si.transform(dataset[['Age','Salary']])
# dataset

In [42]:
#We are using sklearn.preprocessing in Imputer class
#Now, we are using sklearn.impute, SimpleImputr
from sklearn.impute import SimpleImputer
#Make an object of the SimpleImputer class
si = SimpleImputer(missing_values = np.nan, strategy = 'mean',verbose = 0)
#using the object fit the columns on which we want to apply this strategy:
si = si.fit(dataset.iloc[:,1:3]) #Can give seprate column location in the list.
#Dataset without missing values
dataset.iloc[:,1:3] = si.transform(dataset.iloc[:,1:3])
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

Step 3: Identifying all the independent variable x; Identifying all the dependent variable y (which our machine will predict)

In [43]:
x = dataset.iloc[:,:3]
x

Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [44]:
y = dataset.iloc[:,3]
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

Step 4: Taking care of catogorical values: (We have to convert strings into numerical values)

In [45]:
from sklearn.preprocessing import LabelEncoder

In [46]:
#Create an object:
labelencoder_x  = LabelEncoder()
#x.iloc[:,0]

In [47]:
x.iloc[:, 0] = labelencoder_x.fit_transform(x.iloc[:, 0])
x

Country        Age        Salary
0        0  44.000000  72000.000000
1        2  27.000000  48000.000000
2        1  30.000000  54000.000000
3        2  38.000000  61000.000000
4        1  40.000000  63777.777778
5        0  35.000000  58000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
8        1  50.000000  83000.000000
9        0  37.000000  67000.000000

In [48]:
#Since it is assigning the value as 0,1,2 for the country coulumn. We have to change it as 1 for the 

In [49]:
from sklearn.preprocessing import OneHotEncoder

In [50]:
# ohe = OneHotEncoder()
# x = ohe.fit_transform(x).toarray()
# x

In [51]:
from sklearn.compose import ColumnTransformer

In [52]:
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])], remainder='passthrough')
dataset = np.array(columnTransformer.fit_transform(dataset), dtype = np.str)
dataset

array([['1.0', '0.0', '0.0', '44.0', '72000.0', 'No'],
       ['0.0', '0.0', '1.0', '27.0', '48000.0', 'Yes'],
       ['0.0', '1.0', '0.0', '30.0', '54000.0', 'No'],
       ['0.0', '0.0', '1.0', '38.0', '61000.0', 'No'],
       ['0.0', '1.0', '0.0', '40.0', '63777.77777777778', 'Yes'],
       ['1.0', '0.0', '0.0', '35.0', '58000.0', 'Yes'],
       ['0.0', '0.0', '1.0', '38.77777777777778', '52000.0', 'No'],
       ['1.0', '0.0', '0.0', '48.0', '79000.0', 'Yes'],
       ['0.0', '1.0', '0.0', '50.0', '83000.0', 'No'],
       ['1.0', '0.0', '0.0', '37.0', '67000.0', 'Yes']], dtype='<U17')

In [53]:
y = dataset[:,5]
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype='<U17')

In [55]:
#Now converting the purchase column:
from sklearn.preprocessing import LabelEncoder
#Creating an object:
labelencoder_Y = LabelEncoder()
y = labelencoder_Y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

Step 5: Splitting the data into training set and test set:

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [59]:
x_train

Country        Age        Salary
4        1  40.000000  63777.777778
9        0  37.000000  67000.000000
1        2  27.000000  48000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
3        2  38.000000  61000.000000
0        0  44.000000  72000.000000
5        0  35.000000  58000.000000

In [60]:
x_test

Country   Age   Salary
2        1  30.0  54000.0
8        1  50.0  83000.0

In [61]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [62]:
y_test

array([0, 0], dtype=int64)

Step 6: Future Scaling:

Formula:

1. Standardization Formula Xstand => x-mean(x) / standard dev(x)

2. Normalization Formula Xnorm => x-min(x) / (max(x)-min(x))

In [64]:
from sklearn.preprocessing import StandardScaler

In [66]:
sc_x = StandardScaler()

In [67]:
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.fit_transform(x_test)

In [68]:
x_train

array([[ 0.13483997,  0.26306757,  0.12381479],
       [-0.94387981, -0.25350148,  0.46175632],
       [ 1.21355975, -1.97539832, -1.53093341],
       [ 1.21355975,  0.05261351, -1.11141978],
       [-0.94387981,  1.64058505,  1.7202972 ],
       [ 1.21355975, -0.0813118 , -0.16751412],
       [-0.94387981,  0.95182631,  0.98614835],
       [-0.94387981, -0.59788085, -0.48214934]])

In [69]:
x_test

array([[ 0., -1., -1.],
       [ 0.,  1.,  1.]])